apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: warinthornmild/sds-project-frontend:nueng
          ports:
            - containerPort: 5000
          livenessProbe:
            exec:
              command:
                - ls
            initialDelaySeconds: 10
            periodSeconds: 3
