apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    run: order-service
spec:
  ports:
    - port: 5070
      protocol: TCP
      targetPort: 5000
  selector:
    app: order-service
