apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    run: product-service
spec:
  type: LoadBalancer
  ports:
    - port: 5060
      protocol: TCP
      targetPort: 5000
      nodePort: 30002
  selector:
    app: product-service
