apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    run: user-service
spec:
  type: LoadBalancer
  ports:
    - port: 5050
      protocol: TCP
      targetPort: 5000
      nodePort: 30003
  selector:
    app: user-service
