apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      volumes:
        - name: user-db-data
      containers:
        - name: user-db
          image: hypriot/rpi-mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: test
          - name: MYSQL_DATABASE
            value: user
          ports:
          - containerPort: 3306
            name: mysql
          volumeMounts:
            - name: user-db-data
              mountPath: /var/lib/mysql
          # restart: always
        - name: user
          image: warinthornmild/sds-project-user_service
          ports:
            - containerPort: 5000
          # depends_on:
          #   - user_db
          # restart: always
